import { Exercise } from '../types/workout';

export const BUILT_IN_EXERCISES: Omit<Exercise, 'id'>[] = [
  // ── 하체 ──────────────────────────────────────────────────────────────────
  { name_ko: '컨벤셔널 데드리프트', name_en: 'Conventional Deadlift', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '바벨 백스쿼트', name_en: 'Barbell Back Squat', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '스미스머신 스플릿 스쿼트', name_en: 'Smith Machine Split Squat', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '스미스머신 데드리프트', name_en: 'Smith Machine Deadlift', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '스미스머신 스쿼트', name_en: 'Smith Machine Squat', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '덤벨 런지', name_en: 'Dumbbell Lunge', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 고블릿 스쿼트', name_en: 'Dumbbell Goblet Squat', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 스티프 레그 데드리프트', name_en: 'Dumbbell Stiff Leg Deadlift', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '프론트 스쿼트', name_en: 'Front Squat', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '저처 스쿼트', name_en: 'Zercher Squat', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '바벨 불가리안 스플릿 스쿼트', name_en: 'Barbell Bulgarian Split Squat', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '덤벨 불가리안 스플릿 스쿼트', name_en: 'Dumbbell Bulgarian Split Squat', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '덤벨 스플릿 스쿼트', name_en: 'Dumbbell Split Squat', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '맨몸 스플릿 스쿼트', name_en: 'Bodyweight Split Squat', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '에어 스쿼트', name_en: 'Air Squat', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '점프 스쿼트', name_en: 'Jump Squat', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케틀벨 고블릿 스쿼트', name_en: 'Kettlebell Goblet Squat', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '루마니안 데드리프트', name_en: 'Romanian Deadlift', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '스모 데드리프트', name_en: 'Sumo Deadlift', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '레그 프레스', name_en: 'Leg Press', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '레그 컬', name_en: 'Leg Curl', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '레그 익스텐션', name_en: 'Leg Extension', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '스탠딩 카프 레이즈', name_en: 'Standing Calf Raise', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '이너 싸이 머신', name_en: 'Inner Thigh Machine', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '런지', name_en: 'Lunge', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '스텝업', name_en: 'Step-up', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '중량 스텝업', name_en: 'Weighted Step-up', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '힙 쓰러스트', name_en: 'Hip Thrust', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '바벨 힙 쓰러스트', name_en: 'Barbell Hip Thrust', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '브이 스쿼트', name_en: 'V-Squat', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '리버스 브이 스쿼트', name_en: 'Reverse V-Squat', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '글루트 킥백 머신', name_en: 'Glute Kickback Machine', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '힙 어브덕션 머신', name_en: 'Hip Abduction Machine', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '시티드 카프 레이즈', name_en: 'Seated Calf Raise', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '정지 백 스쿼트', name_en: 'Paused Back Squat', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '트랩바 데드리프트', name_en: 'Trap Bar Deadlift', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '케이블 힙 어브덕션', name_en: 'Cable Hip Abduction', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '핵 스쿼트 머신', name_en: 'Hack Squat Machine', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '정지 데드리프트', name_en: 'Paused Deadlift', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '정지 스모 데드리프트', name_en: 'Paused Sumo Deadlift', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '바벨 박스 스쿼트', name_en: 'Barbell Box Squat', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '바벨 프론트 랙 런지', name_en: 'Barbell Front Rack Lunge', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '바벨 점프 스쿼트', name_en: 'Barbell Jump Squat', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '바벨 런지', name_en: 'Barbell Lunge', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '바벨 레터럴 런지', name_en: 'Barbell Lateral Lunge', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '바벨 스플릿 스쿼트', name_en: 'Barbell Split Squat', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '바벨 스탠딩 카프 레이즈', name_en: 'Barbell Standing Calf Raise', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '스티프 레그 데드리프트', name_en: 'Stiff Leg Deadlift', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '맨몸 오버헤드 스쿼트', name_en: 'Bodyweight Overhead Squat', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 스모 스쿼트', name_en: 'Dumbbell Sumo Squat', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 레그 컬', name_en: 'Dumbbell Leg Curl', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 스쿼트', name_en: 'Dumbbell Squat', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '바벨 핵 스쿼트', name_en: 'Barbell Hack Squat', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '시티드 레그 컬', name_en: 'Seated Leg Curl', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '힙 쓰러스트 머신', name_en: 'Hip Thrust Machine', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '맨몸 카프 레이즈', name_en: 'Bodyweight Calf Raise', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '글루트 브릿지', name_en: 'Glute Bridge', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '덤벨 루마니안 데드리프트', name_en: 'Dumbbell Romanian Deadlift', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '라잉 힙 어브덕션', name_en: 'Lying Hip Abduction', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '싱글 레그 글루트 브릿지', name_en: 'Single Leg Glute Bridge', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '피스톨 박스 스쿼트', name_en: 'Pistol Box Squat', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '사이드 라잉 클램', name_en: 'Side Lying Clam', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '맨몸 원레그 데드리프트', name_en: 'Bodyweight Single Leg Deadlift', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '바벨 원레그 데드리프트', name_en: 'Barbell Single Leg Deadlift', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '덤벨 원레그 데드리프트', name_en: 'Dumbbell Single Leg Deadlift', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '케틀벨 데드리프트', name_en: 'Kettlebell Deadlift', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '케틀벨 스모 데드리프트', name_en: 'Kettlebell Sumo Deadlift', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '덤벨 스모 데드리프트', name_en: 'Dumbbell Sumo Deadlift', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '덤벨 레터럴 런지', name_en: 'Dumbbell Lateral Lunge', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케틀벨 레터럴 런지', name_en: 'Kettlebell Lateral Lunge', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '맨몸 레터럴 런지', name_en: 'Bodyweight Lateral Lunge', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '원레그 익스텐션', name_en: 'Single Leg Extension', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '원레그 컬', name_en: 'Single Leg Curl', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '원레그 프레스', name_en: 'Single Leg Press', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '수평 레그 프레스', name_en: 'Horizontal Leg Press', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '수평 원레그 프레스', name_en: 'Horizontal Single Leg Press', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '시티드 원레그 컬', name_en: 'Seated Single Leg Curl', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '노르딕 햄스트링 컬', name_en: 'Nordic Hamstring Curl', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '바벨 스모 스쿼트', name_en: 'Barbell Sumo Squat', category: '하체', default_rest_seconds: 150, is_custom: false },
  { name_ko: '케틀벨 스모 스쿼트', name_en: 'Kettlebell Sumo Squat', category: '하체', default_rest_seconds: 120, is_custom: false },
  { name_ko: '스모 에어 스쿼트', name_en: 'Sumo Air Squat', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '피스톨 스쿼트', name_en: 'Pistol Squat', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덩키 킥', name_en: 'Donkey Kick', category: '하체', default_rest_seconds: 60, is_custom: false },
  { name_ko: '케이블 덩키 킥', name_en: 'Cable Donkey Kick', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '데피싯 데드리프트', name_en: 'Deficit Deadlift', category: '하체', default_rest_seconds: 180, is_custom: false },
  { name_ko: '런지 트위스트', name_en: 'Lunge Twist', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케틀벨 런지 트위스트', name_en: 'Kettlebell Lunge Twist', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 풀 스루', name_en: 'Cable Pull Through', category: '하체', default_rest_seconds: 90, is_custom: false },
  { name_ko: '몬스터 글루트 머신', name_en: 'Monster Glute Machine', category: '하체', default_rest_seconds: 120, is_custom: false },

  // ── 어깨 ──────────────────────────────────────────────────────────────────
  { name_ko: '오버헤드 프레스', name_en: 'Overhead Press', category: '어깨', default_rest_seconds: 180, is_custom: false },
  { name_ko: '스미스머신 오버헤드 프레스', name_en: 'Smith Machine Overhead Press', category: '어깨', default_rest_seconds: 150, is_custom: false },
  { name_ko: '스미스머신 슈러그', name_en: 'Smith Machine Shrug', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 숄더 프레스', name_en: 'Dumbbell Shoulder Press', category: '어깨', default_rest_seconds: 120, is_custom: false },
  { name_ko: '덤벨 레터럴 레이즈', name_en: 'Dumbbell Lateral Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '벤트오버 덤벨 레터럴 레이즈', name_en: 'Bent-Over Dumbbell Lateral Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '아놀드 덤벨 프레스', name_en: 'Arnold Dumbbell Press', category: '어깨', default_rest_seconds: 120, is_custom: false },
  { name_ko: '숄더 프레스 머신', name_en: 'Shoulder Press Machine', category: '어깨', default_rest_seconds: 120, is_custom: false },
  { name_ko: '비하인드 넥 프레스', name_en: 'Behind the Neck Press', category: '어깨', default_rest_seconds: 150, is_custom: false },
  { name_ko: '덤벨 프론트 레이즈', name_en: 'Dumbbell Front Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 슈러그', name_en: 'Dumbbell Shrug', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '바벨 슈러그', name_en: 'Barbell Shrug', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '페이스 풀', name_en: 'Face Pull', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '핸드스탠드', name_en: 'Handstand', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '핸드스탠드 푸시업', name_en: 'Handstand Push-up', category: '어깨', default_rest_seconds: 120, is_custom: false },
  { name_ko: '케이블 리버스 플라이', name_en: 'Cable Reverse Fly', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '바벨 업라이트 로우', name_en: 'Barbell Upright Row', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 업라이트 로우', name_en: 'Dumbbell Upright Row', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '이지바 업라이트 로우', name_en: 'EZ Bar Upright Row', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '푸시 프레스', name_en: 'Push Press', category: '어깨', default_rest_seconds: 150, is_custom: false },
  { name_ko: '리어 델토이드 플라이 머신', name_en: 'Rear Deltoid Fly Machine', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '레터럴 레이즈 머신', name_en: 'Lateral Raise Machine', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 레터럴 레이즈', name_en: 'Cable Lateral Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 프론트 레이즈', name_en: 'Cable Front Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '이지바 프론트 레이즈', name_en: 'EZ Bar Front Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '시티드 덤벨 리어 레터럴 레이즈', name_en: 'Seated Dumbbell Rear Lateral Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '숄더 탭', name_en: 'Shoulder Tap', category: '어깨', default_rest_seconds: 60, is_custom: false },
  { name_ko: '시티드 바벨 숄더 프레스', name_en: 'Seated Barbell Shoulder Press', category: '어깨', default_rest_seconds: 150, is_custom: false },
  { name_ko: '시티드 덤벨 숄더 프레스', name_en: 'Seated Dumbbell Shoulder Press', category: '어깨', default_rest_seconds: 120, is_custom: false },
  { name_ko: '플레이트 숄더 프레스', name_en: 'Plate Shoulder Press', category: '어깨', default_rest_seconds: 120, is_custom: false },
  { name_ko: 'Y 레이즈', name_en: 'Y-Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 Y 레이즈', name_en: 'Dumbbell Y-Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '슈러그 머신', name_en: 'Shrug Machine', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 슈러그', name_en: 'Cable Shrug', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 인터널 로테이션', name_en: 'Cable Internal Rotation', category: '어깨', default_rest_seconds: 60, is_custom: false },
  { name_ko: '케이블 익스터널 로테이션', name_en: 'Cable External Rotation', category: '어깨', default_rest_seconds: 60, is_custom: false },
  { name_ko: '원암 케이블 레터럴 레이즈', name_en: 'One-Arm Cable Lateral Raise', category: '어깨', default_rest_seconds: 90, is_custom: false },
  { name_ko: '랜드마인 프레스', name_en: 'Landmine Press', category: '어깨', default_rest_seconds: 120, is_custom: false },
  { name_ko: '원암 랜드마인 프레스', name_en: 'One-Arm Landmine Press', category: '어깨', default_rest_seconds: 120, is_custom: false },

  // ── 가슴 ──────────────────────────────────────────────────────────────────
  { name_ko: '벤치프레스', name_en: 'Bench Press', category: '가슴', default_rest_seconds: 180, is_custom: false },
  { name_ko: '스미스머신 벤치프레스', name_en: 'Smith Machine Bench Press', category: '가슴', default_rest_seconds: 150, is_custom: false },
  { name_ko: '스미스머신 인클라인 벤치프레스', name_en: 'Smith Machine Incline Bench Press', category: '가슴', default_rest_seconds: 150, is_custom: false },
  { name_ko: '덤벨 벤치프레스', name_en: 'Dumbbell Bench Press', category: '가슴', default_rest_seconds: 120, is_custom: false },
  { name_ko: '인클라인 덤벨 벤치프레스', name_en: 'Incline Dumbbell Bench Press', category: '가슴', default_rest_seconds: 120, is_custom: false },
  { name_ko: '덤벨 플라이', name_en: 'Dumbbell Fly', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '스탠딩 케이블 플라이', name_en: 'Standing Cable Fly', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '인클라인 벤치프레스', name_en: 'Incline Bench Press', category: '가슴', default_rest_seconds: 150, is_custom: false },
  { name_ko: '딥스', name_en: 'Dips', category: '가슴', default_rest_seconds: 120, is_custom: false },
  { name_ko: '중량 딥스', name_en: 'Weighted Dips', category: '가슴', default_rest_seconds: 150, is_custom: false },
  { name_ko: '인클라인 덤벨 플라이', name_en: 'Incline Dumbbell Fly', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '푸시업', name_en: 'Push-up', category: '가슴', default_rest_seconds: 60, is_custom: false },
  { name_ko: '중량 푸시업', name_en: 'Weighted Push-up', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '힌두 푸시업', name_en: 'Hindu Push-up', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '아처 푸시업', name_en: 'Archer Push-up', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '클로즈그립 푸시업', name_en: 'Close-Grip Push-up', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '체스트 프레스 머신', name_en: 'Chest Press Machine', category: '가슴', default_rest_seconds: 120, is_custom: false },
  { name_ko: '펙덱 플라이 머신', name_en: 'Pec Deck Fly Machine', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '인클라인 벤치프레스 머신', name_en: 'Incline Bench Press Machine', category: '가슴', default_rest_seconds: 120, is_custom: false },
  { name_ko: '덤벨 풀오버', name_en: 'Dumbbell Pullover', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '시티드 딥스 머신', name_en: 'Seated Dips Machine', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '로우 풀리 케이블 플라이', name_en: 'Low Pulley Cable Fly', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '해머 벤치프레스', name_en: 'Hammer Bench Press', category: '가슴', default_rest_seconds: 150, is_custom: false },
  { name_ko: '스포토 벤치프레스', name_en: 'Spoto Bench Press', category: '가슴', default_rest_seconds: 180, is_custom: false },
  { name_ko: '어시스트 딥스 머신', name_en: 'Assisted Dips Machine', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '디클라인 벤치프레스', name_en: 'Decline Bench Press', category: '가슴', default_rest_seconds: 150, is_custom: false },
  { name_ko: '바벨 플로어 프레스', name_en: 'Barbell Floor Press', category: '가슴', default_rest_seconds: 150, is_custom: false },
  { name_ko: '클랩 푸시업', name_en: 'Clap Push-up', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '디클라인 덤벨 플라이', name_en: 'Decline Dumbbell Fly', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '인클라인 푸시업', name_en: 'Incline Push-up', category: '가슴', default_rest_seconds: 60, is_custom: false },
  { name_ko: '파이크 푸시업', name_en: 'Pike Push-up', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '디클라인 체스트 프레스 머신', name_en: 'Decline Chest Press Machine', category: '가슴', default_rest_seconds: 120, is_custom: false },
  { name_ko: '인클라인 덤벨 트위스트 프레스', name_en: 'Incline Dumbbell Twist Press', category: '가슴', default_rest_seconds: 120, is_custom: false },
  { name_ko: '인클라인 케이블 플라이', name_en: 'Incline Cable Fly', category: '가슴', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 스퀴즈 프레스', name_en: 'Dumbbell Squeeze Press', category: '가슴', default_rest_seconds: 120, is_custom: false },

  // ── 팔 ──────────────────────────────────────────────────────────────────
  { name_ko: '덤벨 트라이셉 익스텐션', name_en: 'Dumbbell Tricep Extension', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 킥백', name_en: 'Dumbbell Kickback', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 푸시 다운', name_en: 'Cable Push Down', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '바벨 컬', name_en: 'Barbell Curl', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '이지바 컬', name_en: 'EZ Bar Curl', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 해머 컬', name_en: 'Dumbbell Hammer Curl', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '클로즈 그립 벤치프레스', name_en: 'Close Grip Bench Press', category: '팔', default_rest_seconds: 150, is_custom: false },
  { name_ko: '시티드 덤벨 트라이셉 익스텐션', name_en: 'Seated Dumbbell Tricep Extension', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 트라이셉 익스텐션', name_en: 'Cable Tricep Extension', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '바벨 리스트 컬', name_en: 'Barbell Wrist Curl', category: '팔', default_rest_seconds: 60, is_custom: false },
  { name_ko: '이지바 리스트 컬', name_en: 'EZ Bar Wrist Curl', category: '팔', default_rest_seconds: 60, is_custom: false },
  { name_ko: '덤벨 리스트 컬', name_en: 'Dumbbell Wrist Curl', category: '팔', default_rest_seconds: 60, is_custom: false },
  { name_ko: '스컬 크러셔', name_en: 'Skull Crusher', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '바벨 라잉 트라이셉 익스텐션', name_en: 'Barbell Lying Tricep Extension', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 프리쳐 컬', name_en: 'Dumbbell Preacher Curl', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '바벨 프리쳐 컬', name_en: 'Barbell Preacher Curl', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '이지바 프리쳐 컬', name_en: 'EZ Bar Preacher Curl', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '프리쳐 컬 머신', name_en: 'Preacher Curl Machine', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '암 컬 머신', name_en: 'Arm Curl Machine', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 해머컬', name_en: 'Cable Hammer Curl', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 오버헤드 트라이셉 익스텐션', name_en: 'Cable Overhead Tricep Extension', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '케이블 라잉 트라이셉 익스텐션', name_en: 'Cable Lying Tricep Extension', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '리버스 바벨 리스트 컬', name_en: 'Reverse Barbell Wrist Curl', category: '팔', default_rest_seconds: 60, is_custom: false },
  { name_ko: '리버스 덤벨 리스트 컬', name_en: 'Reverse Dumbbell Wrist Curl', category: '팔', default_rest_seconds: 60, is_custom: false },
  { name_ko: '인클라인 덤벨 컬', name_en: 'Incline Dumbbell Curl', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '벤치 딥스', name_en: 'Bench Dips', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '리스트 롤러', name_en: 'Wrist Roller', category: '팔', default_rest_seconds: 60, is_custom: false },
  { name_ko: '리버스 바벨 컬', name_en: 'Reverse Barbell Curl', category: '팔', default_rest_seconds: 90, is_custom: false },
  { name_ko: '트라이셉 익스텐션 머신', name_en: 'Tricep Extension Machine', category: '팔', default_rest_seconds: 90, is_custom: false },

  // ── 복근 ──────────────────────────────────────────────────────────────────
  { name_ko: '싯업', name_en: 'Sit-up', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '크런치', name_en: 'Crunch', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '힐 터치', name_en: 'Heel Touch', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '레그 레이즈', name_en: 'Leg Raise', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '행잉 레그 레이즈', name_en: 'Hanging Leg Raise', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '할로우 락', name_en: 'Hollow Rock', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '할로우 포지션', name_en: 'Hollow Position', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '플랭크', name_en: 'Plank', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '덤벨 사이드 벤드', name_en: 'Dumbbell Side Bend', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '복근 롤아웃', name_en: 'Ab Rollout', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '복근 에어 바이크', name_en: 'Air Bike Crunches', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '행잉 니 레이즈', name_en: 'Hanging Knee Raise', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '복근 크런치 머신', name_en: 'Ab Crunch Machine', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '행 클린', name_en: 'Hang Clean', category: '복근', default_rest_seconds: 150, is_custom: false },
  { name_ko: '행 스내치', name_en: 'Hang Snatch', category: '복근', default_rest_seconds: 150, is_custom: false },
  { name_ko: '필라테스 잭나이프', name_en: 'Pilates Jackknife', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '리버스 크런치', name_en: 'Reverse Crunch', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '사이드 플랭크', name_en: 'Side Plank', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '45도 사이드 벤드', name_en: '45-degree Side Bend', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: 'RKC 플랭크', name_en: 'RKC Plank', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '케이블 사이드 벤드', name_en: 'Cable Side Bend', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '중량 디클라인 크런치', name_en: 'Weighted Decline Crunch', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '디클라인 리버스 크런치', name_en: 'Decline Reverse Crunch', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '디클라인 싯업', name_en: 'Decline Sit-up', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '중량 디클라인 싯업', name_en: 'Weighted Decline Sit-up', category: '복근', default_rest_seconds: 90, is_custom: false },
  { name_ko: '사이드 크런치', name_en: 'Side Crunch', category: '복근', default_rest_seconds: 60, is_custom: false },
  { name_ko: '케이블 트위스트', name_en: 'Cable Twist', category: '복근', default_rest_seconds: 90, is_custom: false },

  // ── 등 ────────────────────────────────────────────────────────────────────
  { name_ko: '스미스머신 로우', name_en: 'Smith Machine Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '덤벨 로우', name_en: 'Dumbbell Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '원암 덤벨 로우', name_en: 'One-Arm Dumbbell Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '케이블 암 풀다운', name_en: 'Cable Arm Pulldown', category: '등', default_rest_seconds: 90, is_custom: false },
  { name_ko: '시티드 케이블 로우', name_en: 'Seated Cable Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '굿모닝 엑서사이즈', name_en: 'Good Morning Exercise', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '풀업', name_en: 'Pull-up', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '중량 풀업', name_en: 'Weighted Pull-up', category: '등', default_rest_seconds: 150, is_custom: false },
  { name_ko: '친업', name_en: 'Chin-up', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '중량 친업', name_en: 'Weighted Chin-up', category: '등', default_rest_seconds: 150, is_custom: false },
  { name_ko: '인클라인 바벨 로우', name_en: 'Incline Barbell Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '인클라인 덤벨 로우', name_en: 'Incline Dumbbell Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '인버티드 로우', name_en: 'Inverted Row', category: '등', default_rest_seconds: 90, is_custom: false },
  { name_ko: '바벨 풀오버', name_en: 'Barbell Pullover', category: '등', default_rest_seconds: 90, is_custom: false },
  { name_ko: '시티드 로우 머신', name_en: 'Seated Row Machine', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '랫풀다운', name_en: 'Lat Pulldown', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '중량 하이퍼 익스텐션', name_en: 'Weighted Hyperextension', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '백 익스텐션', name_en: 'Back Extension', category: '등', default_rest_seconds: 90, is_custom: false },
  { name_ko: '티바 로우 머신', name_en: 'T-Bar Row Machine', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '맥그립 랫풀다운', name_en: 'MAG Grip Lat Pulldown', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '패러럴그립 랫풀다운', name_en: 'Parallel Grip Lat Pulldown', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '언더그립 랫풀다운', name_en: 'Underhand Grip Lat Pulldown', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '정지 바벨 로우', name_en: 'Paused Barbell Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '어시스트 풀업 머신', name_en: 'Assisted Pull-up Machine', category: '등', default_rest_seconds: 90, is_custom: false },
  { name_ko: '플로어 시티드 케이블 로우', name_en: 'Floor Seated Cable Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '언더그립 바벨 로우', name_en: 'Underhand Grip Barbell Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '라잉 바벨 로우', name_en: 'Lying Barbell Row', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '비하인드 넥 풀다운', name_en: 'Behind the Neck Pulldown', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '원암 케이블 풀다운', name_en: 'One-Arm Cable Pulldown', category: '등', default_rest_seconds: 90, is_custom: false },
  { name_ko: '원암 레터럴 와이드 풀다운', name_en: 'One-Arm Lateral Wide Pulldown', category: '등', default_rest_seconds: 90, is_custom: false },
  { name_ko: '로우 로우 머신', name_en: 'Low Row Machine', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '원암 로우 로우 머신', name_en: 'One-Arm Low Row Machine', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '하이 로우 머신', name_en: 'High Row Machine', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '언더그립 하이 로우 머신', name_en: 'Underhand Grip High Row Machine', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '원암 하이 로우 머신', name_en: 'One-Arm High Row Machine', category: '등', default_rest_seconds: 120, is_custom: false },
  { name_ko: '원암 시티드 케이블 로우', name_en: 'One-Arm Seated Cable Row', category: '등', default_rest_seconds: 120, is_custom: false },

  // ── 역도 ──────────────────────────────────────────────────────────────────
  { name_ko: '클린', name_en: 'Clean', category: '역도', default_rest_seconds: 180, is_custom: false },
  { name_ko: '클린 & 저크', name_en: 'Clean & Jerk', category: '역도', default_rest_seconds: 180, is_custom: false },
  { name_ko: '저크', name_en: 'Jerk', category: '역도', default_rest_seconds: 180, is_custom: false },
  { name_ko: '스내치', name_en: 'Snatch', category: '역도', default_rest_seconds: 180, is_custom: false },
  { name_ko: '바벨 오버헤드 스쿼트', name_en: 'Barbell Overhead Squat', category: '역도', default_rest_seconds: 180, is_custom: false },
  { name_ko: '덤벨 스내치', name_en: 'Dumbbell Snatch', category: '역도', default_rest_seconds: 120, is_custom: false },
  { name_ko: '케틀벨 스내치', name_en: 'Kettlebell Snatch', category: '역도', default_rest_seconds: 120, is_custom: false },
  { name_ko: '스내치 밸런스', name_en: 'Snatch Balance', category: '역도', default_rest_seconds: 150, is_custom: false },
  { name_ko: '중량 행잉 니 레이즈', name_en: 'Weighted Hanging Knee Raise', category: '역도', default_rest_seconds: 90, is_custom: false },
  { name_ko: '클린 하이풀', name_en: 'Clean High Pull', category: '역도', default_rest_seconds: 150, is_custom: false },
  { name_ko: '스내치 하이풀', name_en: 'Snatch High Pull', category: '역도', default_rest_seconds: 150, is_custom: false },

  // ── 유산소 ────────────────────────────────────────────────────────────────
  { name_ko: '트레드밀', name_en: 'Treadmill', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '싸이클', name_en: 'Cycling', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '로잉 머신', name_en: 'Rowing Machine', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '계단 오르기', name_en: 'Stair Climbing', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '줄넘기', name_en: 'Jumping Rope', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '이단 뛰기', name_en: 'Double Under', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '하이니 스킵', name_en: 'High Knee Skip', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '어썰트 바이크', name_en: 'Assault Bike', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '스텝밀', name_en: 'StepMill', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '걷기', name_en: 'Walking', category: '유산소', default_rest_seconds: 0, is_custom: false },
  { name_ko: '달리기', name_en: 'Running', category: '유산소', default_rest_seconds: 0, is_custom: false },

  // ── 기타 ──────────────────────────────────────────────────────────────────
  { name_ko: '쓰러스터', name_en: 'Thruster', category: '기타', default_rest_seconds: 120, is_custom: false },
  { name_ko: '버피', name_en: 'Burpee', category: '기타', default_rest_seconds: 60, is_custom: false },
  { name_ko: '케틀벨 스윙', name_en: 'Kettlebell Swing', category: '기타', default_rest_seconds: 90, is_custom: false },
  { name_ko: '파머스 워크', name_en: 'Farmer\'s Walk', category: '기타', default_rest_seconds: 60, is_custom: false },
  { name_ko: '월볼 샷', name_en: 'Wall Ball Shot', category: '기타', default_rest_seconds: 90, is_custom: false },
  { name_ko: '마운틴 클라이머', name_en: 'Mountain Climber', category: '기타', default_rest_seconds: 60, is_custom: false },
  { name_ko: '박스 점프', name_en: 'Box Jump', category: '기타', default_rest_seconds: 90, is_custom: false },
  { name_ko: '점핑 잭', name_en: 'Jumping Jack', category: '기타', default_rest_seconds: 60, is_custom: false },
  { name_ko: '바 머슬업', name_en: 'Bar Muscle-up', category: '기타', default_rest_seconds: 120, is_custom: false },
  { name_ko: '링 머슬업', name_en: 'Ring Muscle-up', category: '기타', default_rest_seconds: 120, is_custom: false },
  { name_ko: '덤벨 버피', name_en: 'Dumbbell Burpee', category: '기타', default_rest_seconds: 90, is_custom: false },
  { name_ko: '덤벨 쓰러스터', name_en: 'Dumbbell Thruster', category: '기타', default_rest_seconds: 120, is_custom: false },
  { name_ko: '인치웜', name_en: 'Inchworm', category: '기타', default_rest_seconds: 60, is_custom: false },
  { name_ko: '스모 데드리프트 하이풀', name_en: 'Sumo Deadlift High Pull', category: '기타', default_rest_seconds: 150, is_custom: false },
  { name_ko: '케틀벨 스모 하이풀', name_en: 'Kettlebell Sumo High Pull', category: '기타', default_rest_seconds: 120, is_custom: false },
];
