ALTER TABLE exercises
  ADD COLUMN IF NOT EXISTS overview_en TEXT,
  ADD COLUMN IF NOT EXISTS overview_ko TEXT,
  ADD COLUMN IF NOT EXISTS why_en TEXT,
  ADD COLUMN IF NOT EXISTS why_ko TEXT,
  ADD COLUMN IF NOT EXISTS how_en TEXT,
  ADD COLUMN IF NOT EXISTS how_ko TEXT;
