-- Generated by scripts/generate-missing-exercise-guide-backfill.js
BEGIN;

WITH target_names(name_ko) AS (
  VALUES
    ('덤벨 스퀴즈 프레스'),
    ('덤벨 풀오버'),
    ('디클라인 덤벨 플라이'),
    ('디클라인 체스트 프레스 머신'),
    ('로우 풀리 케이블 플라이'),
    ('바벨 플로어 프레스'),
    ('벤치프레스'),
    ('스미스머신 벤치프레스'),
    ('스미스머신 인클라인 벤치프레스'),
    ('스포토 벤치프레스'),
    ('시티드 딥스 머신'),
    ('아처 푸시업'),
    ('어시스트 딥스 머신'),
    ('인클라인 덤벨 트위스트 프레스'),
    ('인클라인 덤벨 플라이'),
    ('인클라인 벤치프레스 머신'),
    ('인클라인 케이블 플라이'),
    ('인클라인 푸시업'),
    ('중량 딥스'),
    ('중량 푸시업'),
    ('체스트 프레스 머신'),
    ('클랩 푸시업'),
    ('클로즈그립 벤치프레스'),
    ('클로즈그립 푸시업'),
    ('파이크 푸시업'),
    ('푸시업'),
    ('해머 벤치프레스'),
    ('힌두 푸시업'),
    ('덤벨 버피'),
    ('덤벨 쓰러스터'),
    ('링 머슬업'),
    ('마운틴 클라이머'),
    ('바 머슬업'),
    ('박스 점프'),
    ('버피'),
    ('스모 데드리프트 하이풀'),
    ('쓰러스터'),
    ('월볼 샷'),
    ('인치웜'),
    ('점핑 잭'),
    ('케틀벨 스모 하이풀'),
    ('케틀벨 스윙'),
    ('파머스 워크'),
    ('라잉 바벨 로우'),
    ('로우 로우 머신'),
    ('맥그립 랫풀다운'),
    ('바벨 풀오버'),
    ('백 익스텐션'),
    ('비하인드 넥 풀다운'),
    ('스미스머신 로우'),
    ('어시스트 풀업 머신'),
    ('언더그립 랫풀다운'),
    ('언더그립 바벨 로우'),
    ('언더그립 하이 로우 머신'),
    ('원암 덤벨 로우'),
    ('원암 레터럴 와이드 풀다운'),
    ('원암 로우 로우 머신'),
    ('원암 시티드 케이블 로우'),
    ('원암 케이블 풀다운'),
    ('원암 하이 로우 머신'),
    ('인버티드 로우'),
    ('인클라인 덤벨 로우'),
    ('인클라인 바벨 로우'),
    ('정지 바벨 로우'),
    ('중량 친업'),
    ('중량 풀업'),
    ('중량 하이퍼 익스텐션'),
    ('케이블 암 풀다운'),
    ('패러럴그립 랫풀다운'),
    ('플로어 시티드 케이블 로우'),
    ('하이 로우 머신'),
    ('45도 사이드 벤드'),
    ('RKC 플랭크'),
    ('덤벨 사이드 벤드'),
    ('디클라인 리버스 크런치'),
    ('디클라인 싯업'),
    ('리버스 크런치'),
    ('복근 에어 바이크'),
    ('복근 크런치 머신'),
    ('사이드 크런치'),
    ('사이드 플랭크'),
    ('싯업'),
    ('중량 디클라인 싯업'),
    ('중량 디클라인 크런치'),
    ('케이블 사이드 벤드'),
    ('케이블 트위스트'),
    ('필라테스 잭나이프'),
    ('할로우 락'),
    ('할로우 포지션'),
    ('행 스내치'),
    ('행 클린'),
    ('행잉 니 레이즈'),
    ('힐 터치'),
    ('Y 레이즈'),
    ('덤벨 Y 레이즈'),
    ('덤벨 슈러그'),
    ('덤벨 업라이트 로우'),
    ('덤벨 프론트 레이즈'),
    ('랜드마인 프레스'),
    ('레터럴 레이즈 머신'),
    ('리어 델토이드 플라이 머신'),
    ('바벨 슈러그'),
    ('바벨 업라이트 로우'),
    ('벤트오버 덤벨 레터럴 레이즈'),
    ('비하인드 넥 프레스'),
    ('숄더 탭'),
    ('숄더 프레스 머신'),
    ('슈러그 머신'),
    ('스미스머신 슈러그'),
    ('스미스머신 오버헤드 프레스'),
    ('시티드 덤벨 리어 레터럴 레이즈'),
    ('시티드 덤벨 숄더 프레스'),
    ('시티드 바벨 숄더 프레스'),
    ('오버헤드프레스'),
    ('원암 랜드마인 프레스'),
    ('원암 케이블 레터럴 레이즈'),
    ('이지바 업라이트 로우'),
    ('이지바 프론트 레이즈'),
    ('케이블 레터럴 레이즈'),
    ('케이블 리버스 플라이'),
    ('케이블 슈러그'),
    ('케이블 익스터널 로테이션'),
    ('케이블 인터널 로테이션'),
    ('케이블 프론트 레이즈'),
    ('푸시 프레스'),
    ('플레이트 숄더 프레스'),
    ('핸드스탠드'),
    ('핸드스탠드 푸시업'),
    ('덤벨 스내치'),
    ('바벨 오버헤드 스쿼트'),
    ('스내치'),
    ('스내치 밸런스'),
    ('스내치 하이풀'),
    ('저크'),
    ('중량 행잉 니 레이즈'),
    ('케틀벨 스내치'),
    ('클린'),
    ('클린 & 저크'),
    ('클린 하이풀'),
    ('걷기'),
    ('계단 오르기'),
    ('달리기'),
    ('로잉 머신'),
    ('스텝밀'),
    ('싸이클'),
    ('어썰트 바이크'),
    ('이단 뛰기'),
    ('줄넘기'),
    ('트레드밀'),
    ('하이니 스킵'),
    ('덤벨 리스트 컬'),
    ('덤벨 킥백'),
    ('덤벨 트라이셉 익스텐션'),
    ('덤벨 프리쳐 컬'),
    ('리버스 덤벨 리스트 컬'),
    ('리버스 바벨 리스트 컬'),
    ('리버스 바벨 컬'),
    ('리스트 롤러'),
    ('바벨 라잉 트라이셉 익스텐션'),
    ('바벨 리스트 컬'),
    ('바벨 프리쳐 컬'),
    ('벤치 딥스'),
    ('시티드 덤벨 트라이셉 익스텐션'),
    ('암 컬 머신'),
    ('이지바 리스트 컬'),
    ('이지바 컬'),
    ('이지바 프리쳐 컬'),
    ('케이블 라잉 트라이셉 익스텐션'),
    ('케이블 오버헤드 트라이셉 익스텐션'),
    ('케이블 트라이셉 익스텐션'),
    ('케이블 해머컬'),
    ('트라이셉 익스텐션 머신'),
    ('프리쳐 컬 머신'),
    ('글루트 브릿지'),
    ('글루트 킥백 머신'),
    ('노르딕 햄스트링 컬'),
    ('덤벨 고블릿 스쿼트'),
    ('덤벨 레그 컬'),
    ('덤벨 레터럴 런지'),
    ('덤벨 루마니안 데드리프트'),
    ('덤벨 불가리안 스플릿 스쿼트'),
    ('덤벨 스모 데드리프트'),
    ('덤벨 스모 스쿼트'),
    ('덤벨 스쿼트'),
    ('덤벨 스티프 레그 데드리프트'),
    ('덤벨 스플릿 스쿼트'),
    ('덤벨 원레그 데드리프트'),
    ('덩키 킥'),
    ('데피싯 데드리프트'),
    ('라잉 힙 어브덕션'),
    ('런지 트위스트'),
    ('리버스 브이 스쿼트'),
    ('맨몸 레터럴 런지'),
    ('맨몸 스플릿 스쿼트'),
    ('맨몸 오버헤드 스쿼트'),
    ('맨몸 원레그 데드리프트'),
    ('맨몸 카프 레이즈'),
    ('몬스터 글루트 머신'),
    ('바벨 런지'),
    ('바벨 레터럴 런지'),
    ('바벨 박스 스쿼트'),
    ('바벨 백스쿼트'),
    ('바벨 불가리안 스플릿 스쿼트'),
    ('바벨 스모 스쿼트'),
    ('바벨 스탠딩 카프 레이즈'),
    ('바벨 스플릿 스쿼트'),
    ('바벨 원레그 데드리프트'),
    ('바벨 점프 스쿼트'),
    ('바벨 프론트 랙 런지'),
    ('바벨 핵 스쿼트'),
    ('바벨 힙 쓰러스트'),
    ('브이 스쿼트'),
    ('사이드 라잉 클램'),
    ('수평 레그 프레스'),
    ('수평 원레그 프레스'),
    ('스모 에어 스쿼트'),
    ('스미스머신 데드리프트'),
    ('스미스머신 스쿼트'),
    ('스미스머신 스플릿 스쿼트'),
    ('스탠딩 카프 레이즈'),
    ('스티프 레그 데드리프트'),
    ('시티드 레그 컬'),
    ('시티드 원레그 컬'),
    ('시티드 카프 레이즈'),
    ('싱글 레그 글루트 브릿지'),
    ('에어 스쿼트'),
    ('원레그 익스텐션'),
    ('원레그 컬'),
    ('원레그 프레스'),
    ('이너 싸이 머신'),
    ('저처 스쿼트'),
    ('점프 스쿼트'),
    ('정지 데드리프트'),
    ('정지 백 스쿼트'),
    ('정지 스모 데드리프트'),
    ('중량 스텝업'),
    ('케이블 덩키 킥'),
    ('케이블 풀 스루'),
    ('케이블 힙 어브덕션'),
    ('케틀벨 고블릿 스쿼트'),
    ('케틀벨 데드리프트'),
    ('케틀벨 런지 트위스트'),
    ('케틀벨 레터럴 런지'),
    ('케틀벨 스모 데드리프트'),
    ('케틀벨 스모 스쿼트'),
    ('트랩바 데드리프트'),
    ('피스톨 박스 스쿼트'),
    ('피스톨 스쿼트'),
    ('핵 스쿼트 머신'),
    ('힙 쓰러스트 머신'),
    ('힙 어브덕션 머신'),
    ('고블릿 스쿼트'),
    ('덤벨 런지'),
    ('레그 익스텐션'),
    ('레그 프레스'),
    ('맨몸 스쿼트'),
    ('버피 테스트 (낮은 강도)'),
    ('인클라인 바벨 프레스'),
    ('카프 레이즈 (서서)'),
    ('카프 레이즈 (스탠딩)'),
    ('푸쉬업 (무릎 대고 또는 벽 푸쉬업)')
),
target_exercises AS (
  SELECT DISTINCT
    e.id,
    e.name_ko,
    COALESCE(NULLIF(e.name_en, ''), e.name_ko) AS name_en,
    COALESCE(NULLIF(e.category, ''), '기타') AS category,
    e.overview_ko,
    e.overview_en,
    e.why_ko,
    e.why_en,
    e.how_ko,
    e.how_en,
    e.description_ko,
    e.description_en
  FROM exercises e
  INNER JOIN target_names t ON t.name_ko = e.name_ko
  WHERE e.is_custom = false
),
classified AS (
  SELECT
    te.*,
    CASE te.category
      WHEN '가슴' THEN '가슴, 전면 어깨, 삼두'
      WHEN '등' THEN '광배, 등 상부, 후면 어깨, 이두'
      WHEN '어깨' THEN '전면, 측면, 후면 어깨와 상부 승모'
      WHEN '하체' THEN '대퇴사두, 햄스트링, 둔근, 종아리'
      WHEN '팔' THEN '이두, 삼두, 전완'
      WHEN '복근' THEN '복직근, 복사근, 코어 안정성'
      WHEN '역도' THEN '전신 폭발력, 어깨 안정성, 하체 힘'
      WHEN '유산소' THEN '심폐 지구력, 리듬, 전신 협응'
      ELSE '주요 근육군'
    END AS targets_ko,
    CASE te.category
      WHEN '가슴' THEN 'the chest, front delts, and triceps'
      WHEN '등' THEN 'the lats, upper back, rear delts, and biceps'
      WHEN '어깨' THEN 'the front, side, and rear delts with upper-trap support'
      WHEN '하체' THEN 'the quads, hamstrings, glutes, and calves'
      WHEN '팔' THEN 'the biceps, triceps, and forearms'
      WHEN '복근' THEN 'the rectus abdominis, obliques, and trunk stability'
      WHEN '역도' THEN 'full-body power, shoulder stability, and lower-body drive'
      WHEN '유산소' THEN 'cardiorespiratory endurance, rhythm, and full-body coordination'
      ELSE 'the target muscle group'
    END AS targets_en,
    CASE
      WHEN te.name_ko ~ '(클린|스내치|저크|하이풀|오버헤드 스쿼트)' OR te.category = '역도' THEN 'olympic_lift'
      WHEN te.name_ko ~ '(걷기|계단 오르기|달리기|로잉 머신|스텝밀|싸이클|어썰트 바이크|이단 뛰기|줄넘기|트레드밀|하이니 스킵|점핑 잭|마운틴 클라이머|버피|박스 점프|인치웜|월볼 샷|쓰러스터|테스트|스윙|파머스 워크)' OR te.category = '유산소' THEN 'conditioning'
      WHEN te.name_ko ~ '(플랭크|크런치|싯업|레그 레이즈|트위스트|롤아웃|사이드 벤드|할로우|잭나이프|힐 터치|행잉 니 레이즈)' OR te.category = '복근' THEN 'core'
      WHEN te.name_ko ~ '(푸시다운|익스텐션|스컬 크러셔|스컬크러셔|킥백|벤치 딥스)' THEN 'triceps_iso'
      WHEN te.name_ko ~ '(컬|리스트 컬|리스트 롤러|프리쳐)' THEN 'curl'
      WHEN te.name_ko ~ '(레이즈|플라이|슈러그|업라이트 로우|로테이션|숄더 탭|Y 레이즈)' THEN 'shoulder_accessory'
      WHEN te.name_ko ~ '(풀업|친업|풀다운|로우|머슬업|백 익스텐션|풀오버)' OR te.category = '등' THEN 'pull'
      WHEN te.name_ko ~ '(벤치프레스|벤치 프레스|프레스|푸시업|푸쉬업|딥스|핸드스탠드 푸시업)' OR te.category = '가슴' THEN 'press'
      WHEN te.name_ko ~ '(데드리프트|굿모닝|힙 쓰러스트|글루트 브릿지|풀 스루|스윙)' THEN 'hinge'
      WHEN te.name_ko ~ '(스쿼트|런지|레그 프레스|스텝업|카프 레이즈|어브덕션|클램|덩키 킥|노르딕 햄스트링 컬|글루트 킥백|레그 컬|레그 익스텐션|원레그 컬|원레그 프레스|원레그 익스텐션)' OR te.category = '하체' THEN 'lower_body'
      ELSE 'generic'
    END AS template_key
  FROM target_exercises te
),
generated AS (
  SELECT
    c.id,
    CASE c.template_key
      WHEN 'press' THEN format('%s는 %s 중심의 미는 동작 계열 운동입니다. 상체 전면의 힘을 키우고 프레스 패턴의 안정성과 볼륨을 높이는 데 유용합니다.', c.name_ko, c.targets_ko)
      WHEN 'pull' THEN format('%s는 %s 중심의 당기기 운동입니다. 등과 팔의 협응을 살리면서 상체 후면의 힘과 자세 안정성을 키우는 데 도움이 됩니다.', c.name_ko, c.targets_ko)
      WHEN 'shoulder_accessory' THEN format('%s는 %s에 세밀한 자극을 주는 보조 운동입니다. 비교적 가벼운 중량으로도 목표 부위 감각과 수축 타이밍을 익히기 좋습니다.', c.name_ko, c.targets_ko)
      WHEN 'curl' THEN format('%s는 %s에 집중 자극을 주는 팔 보조 운동입니다. 목표 부위 긴장을 오래 유지하면서 팔 볼륨과 세부 컨트롤을 높이는 데 유리합니다.', c.name_ko, c.targets_ko)
      WHEN 'triceps_iso' THEN format('%s는 %s 중심의 팔 뒤쪽 보조 운동입니다. 삼두 수축을 선명하게 느끼고 프레스 계열의 잠금 구간 힘을 보완하는 데 좋습니다.', c.name_ko, c.targets_ko)
      WHEN 'core' THEN format('%s는 %s를 강화하는 코어 운동입니다. 몸통 안정성과 복압 조절 능력을 키워 다른 복합 운동의 기반을 다지는 데 유용합니다.', c.name_ko, c.targets_ko)
      WHEN 'olympic_lift' THEN format('%s는 %s을 활용하는 폭발적 전신 운동입니다. 빠른 힘 전달과 타이밍, 전신 협응을 함께 다루는 데 적합합니다.', c.name_ko, c.targets_ko)
      WHEN 'conditioning' THEN format('%s는 %s 향상에 초점을 둔 컨디셔닝 운동입니다. 심박수를 끌어올리면서 전신 리듬과 지구력을 함께 끌어올리는 데 효과적입니다.', c.name_ko, c.targets_ko)
      WHEN 'hinge' THEN format('%s는 %s 중심의 힙 힌지 패턴 운동입니다. 후면 사슬을 활용한 힘 전달과 엉덩이 주도 움직임을 익히는 데 좋습니다.', c.name_ko, c.targets_ko)
      WHEN 'lower_body' THEN format('%s는 %s를 고르게 활용하는 하체 운동입니다. 자세 안정성, 하체 힘, 균형 감각을 함께 키우는 데 유용합니다.', c.name_ko, c.targets_ko)
      ELSE format('%s는 %s 중심의 저항성 운동입니다. 기본 근력과 움직임 완성도를 높이는 데 활용할 수 있습니다.', c.name_ko, c.targets_ko)
    END AS overview_ko,
    CASE c.template_key
      WHEN 'press' THEN format('%s is a pressing exercise for %s. It is useful for building front-side upper-body strength, pressing stability, and repeatable technique.', c.name_en, c.targets_en)
      WHEN 'pull' THEN format('%s is a pulling exercise for %s. It helps build back strength, postural balance, and smoother upper-body pulling mechanics.', c.name_en, c.targets_en)
      WHEN 'shoulder_accessory' THEN format('%s is an accessory movement for %s. It is useful for refining shoulder control and creating targeted muscular tension with relatively low load.', c.name_en, c.targets_en)
      WHEN 'curl' THEN format('%s is an arm isolation exercise for %s. It is effective for improving local control, arm size, and elbow-flexor strength.', c.name_en, c.targets_en)
      WHEN 'triceps_iso' THEN format('%s is an accessory exercise that emphasizes %s. It is a practical way to build triceps size and reinforce the lockout portion of pressing movements.', c.name_en, c.targets_en)
      WHEN 'core' THEN format('%s is a core-focused exercise for %s. It improves trunk control, bracing skill, and the ability to keep the torso organized under load.', c.name_en, c.targets_en)
      WHEN 'olympic_lift' THEN format('%s is an explosive full-body lift for %s. It is well suited for training timing, power transfer, and coordinated force production.', c.name_en, c.targets_en)
      WHEN 'conditioning' THEN format('%s is a conditioning exercise aimed at %s. It is effective for raising heart rate, improving work capacity, and building sustainable movement rhythm.', c.name_en, c.targets_en)
      WHEN 'hinge' THEN format('%s is a hip-hinge movement for %s. It reinforces posterior-chain strength, hip drive, and efficient force transfer through the trunk.', c.name_en, c.targets_en)
      WHEN 'lower_body' THEN format('%s is a lower-body movement for %s. It helps build strength, stability, and positional control through the hips, knees, and ankles.', c.name_en, c.targets_en)
      ELSE format('%s is a resistance-training exercise for %s. It can be used to improve strength, hypertrophy, and technical consistency within a broader program.', c.name_en, c.targets_en)
    END AS overview_en,
    CASE c.template_key
      WHEN 'press' THEN '가슴, 어깨, 삼두의 근력과 근비대를 함께 노릴 수 있고, 다른 프레스 계열 운동의 기반이 되는 패턴이라 프로그램 구성 가치가 높습니다.'
      WHEN 'pull' THEN '밀기 운동과 균형을 맞추고 어깨 건강, 자세 개선, 등과 팔의 근비대 향상에 기여합니다. 상체 후면의 힘 전달 패턴을 안정적으로 만들어줍니다.'
      WHEN 'shoulder_accessory' THEN '약한 부위를 보완하고 근육의 수축 감각을 높이며, 복합 운동에서 부족했던 자극을 채우는 데 도움이 됩니다. 볼륨 확보용으로도 활용도가 높습니다.'
      WHEN 'curl' THEN '이두와 전완의 힘을 키워 당기기 운동 보조에 도움이 되고, 팔 라인 발달에도 직접적인 효과를 기대할 수 있습니다.'
      WHEN 'triceps_iso' THEN '삼두 발달은 상완 둘레와 밀기 동작의 마무리 힘에 큰 영향을 줍니다. 보조 운동으로 넣으면 프레스 정체 구간 돌파에도 도움이 됩니다.'
      WHEN 'core' THEN '코어가 강해지면 상하체 힘 전달이 좋아지고 허리 부담을 줄이는 데 도움이 됩니다. 다른 복합 운동의 퍼포먼스를 받쳐주는 기반 역할도 큽니다.'
      WHEN 'olympic_lift' THEN '폭발적인 하체 힘과 상체 고정 능력을 함께 요구하기 때문에 운동 수행 능력과 전신 파워를 높이는 데 효과적입니다. 타이밍과 기술 숙련도 향상에도 큰 도움이 됩니다.'
      WHEN 'conditioning' THEN '유산소 능력과 회복력을 높여 주간 운동량을 소화하기 쉬워지고, 체력 저하 없이 긴 세션을 버티는 기반을 만드는 데 도움이 됩니다.'
      WHEN 'hinge' THEN '후면 사슬을 강하게 만들어 무게를 들어 올리는 능력, 점프와 달리기 같은 폭발적인 움직임, 허리와 골반의 안정성 향상에 도움이 됩니다.'
      WHEN 'lower_body' THEN '하체 근력과 근비대뿐 아니라 일상적인 앉기, 서기, 계단 오르기 같은 움직임에도 직접적인 도움을 줍니다. 스포츠 퍼포먼스와 부상 예방 측면에서도 효율이 높은 편입니다.'
      ELSE '적절한 중량과 반복 수를 조절하면 근력, 근비대, 움직임 숙련도를 함께 높일 수 있어 프로그램 구성 가치가 높습니다.'
    END AS why_ko,
    CASE c.template_key
      WHEN 'press' THEN 'A strong press supports hypertrophy of the chest, shoulders, and triceps while also improving performance in many other upper-body training movements.'
      WHEN 'pull' THEN 'Pulling work is essential for posture, shoulder health, and balanced upper-body development. It also supports stronger performance in pressing and grip-demanding exercises.'
      WHEN 'shoulder_accessory' THEN 'This makes it effective for bringing up weak points, improving mind-muscle connection, and supplementing the work done by bigger compound lifts.'
      WHEN 'curl' THEN 'Consistent curling work can improve pulling assistance, forearm involvement, and overall arm development while being easy to recover from relative to larger lifts.'
      WHEN 'triceps_iso' THEN 'Developing the triceps improves arm development and can help support progress in presses, dips, and other upper-body pushing patterns.'
      WHEN 'core' THEN 'A stronger core improves force transfer between the upper and lower body, supports spinal positioning, and contributes to better performance in compound lifts and daily movement.'
      WHEN 'olympic_lift' THEN 'These lifts are valuable for building athletic power, full-body coordination, and speed under load while demanding precise technical control.'
      WHEN 'conditioning' THEN 'Improving conditioning supports recovery between sets, raises overall work capacity, and helps maintain performance quality across longer sessions.'
      WHEN 'hinge' THEN 'This pattern is excellent for developing posterior-chain strength, improving athletic power, and building resilience in movements that involve lifting, hinging, and accelerating.'
      WHEN 'lower_body' THEN 'It is valuable for lower-body strength, hypertrophy, athletic performance, and day-to-day movement capacity. It also helps improve balance and force production through the legs.'
      ELSE 'With appropriate loading and repetition schemes, this movement can improve muscular development and movement quality while fitting a wide range of goals.'
    END AS why_en,
    CASE c.template_key
      WHEN 'press' THEN E'견갑을 안정적으로 고정하고 손목, 팔꿈치, 어깨 라인을 편안하게 맞춥니다.\n내려가는 구간은 천천히 통제하고 목표 지점에서 반동 없이 멈춥니다.\n지면이나 벤치에 힘을 전달하며 밀어 올리고, 마무리에서도 어깨 위치를 무너지지 않게 유지합니다.'
      WHEN 'pull' THEN E'가슴을 열고 어깨를 과하게 으쓱하지 않은 상태에서 시작 자세를 잡습니다.\n손보다 팔꿈치를 움직인다는 느낌으로 당기며 목표 부위를 수축합니다.\n끝 지점에서 잠깐 멈춘 뒤 천천히 돌아오며 이완 구간도 통제합니다.'
      WHEN 'shoulder_accessory' THEN E'시작 자세에서 코어를 가볍게 고정하고 반동을 최소화할 준비를 합니다.\n가동 범위 안에서 천천히 들어 올리거나 벌리며 목표 부위 수축에 집중합니다.\n상단에서 잠깐 멈춘 뒤 통제하며 내려오고, 긴장이 완전히 풀리기 전에 다음 반복으로 넘어갑니다.'
      WHEN 'curl' THEN E'상완이 흔들리지 않도록 팔꿈치 위치를 먼저 고정합니다.\n손목을 과하게 꺾지 않은 채 목표 부위 힘으로 천천히 들어 올립니다.\n상단 수축 후 천천히 내려오며 이완 구간에서도 텐션을 유지합니다.'
      WHEN 'triceps_iso' THEN E'팔꿈치 위치를 몸 가까이 고정하고 어깨가 따라 움직이지 않게 세팅합니다.\n팔꿈치를 축으로 사용하며 목표 부위 힘으로 밀거나 펴줍니다.\n수축 지점에서 잠깐 멈춘 뒤 천천히 돌아오며 텐션을 유지합니다.'
      WHEN 'core' THEN E'갈비뼈와 골반 간격을 과하게 벌리지 말고 복부에 힘을 먼저 줍니다.\n반동보다 통제에 집중하며 목표 범위에서 천천히 움직입니다.\n허리가 꺾이거나 목에 힘이 몰리지 않게 유지한 채 반복을 마무리합니다.'
      WHEN 'olympic_lift' THEN E'시작 자세에서 발 압력과 호흡을 정리하고, 바벨이나 도구가 몸에서 멀어지지 않게 준비합니다.\n하체로 지면을 강하게 밀며 폭발적으로 힘을 전달하고, 팔은 타이밍에 맞춰 보조적으로 사용합니다.\n받아내는 자세나 마무리 자세에서도 중심을 잃지 않고, 반복마다 같은 경로와 리듬을 유지합니다.'
      WHEN 'conditioning' THEN E'현재 체력 수준에 맞는 속도와 리듬을 먼저 정하고, 호흡이 무너지지 않게 출발합니다.\n반복이 이어져도 동작 범위와 자세 기준을 유지하며 불필요한 힘 손실을 줄입니다.\n세트가 끝날 때까지 페이스를 조절하고, 회복 구간에서는 호흡과 자세를 빠르게 정리합니다.'
      WHEN 'hinge' THEN E'발과 도구의 거리를 맞추고 코어를 단단히 조여 척추 중립을 유지합니다.\n허리를 꺾지 말고 엉덩이를 뒤로 접으며 내려가 목표 위치를 잡습니다.\n발로 지면을 밀고 엉덩이를 앞으로 보내며 올라오되 상체와 바가 몸에서 멀어지지 않게 합니다.'
      WHEN 'lower_body' THEN E'발 위치를 안정적으로 세팅하고 복부에 힘을 준 뒤 상체 각도를 유지합니다.\n엉덩이와 무릎을 함께 굽혀 내려가며 무릎은 발끝 방향과 비슷하게 움직이게 합니다.\n발바닥 전체로 지면을 밀어 올라오며 상체와 골반이 동시에 일어나도록 컨트롤합니다.'
      ELSE E'시작 자세를 안정적으로 만든 뒤 코어와 호흡을 먼저 정리합니다.\n가동 범위 안에서 반동 없이 목표 부위 힘으로 움직입니다.\n마무리 자세까지 통제한 뒤 같은 패턴으로 반복합니다.'
    END AS how_ko,
    CASE c.template_key
      WHEN 'press' THEN E'Create a stable shoulder position and line up the wrists, elbows, and pressing path.\nControl the lowering phase without losing tension or bouncing out of the bottom.\nPress smoothly while keeping the shoulders organized and the torso stable.'
      WHEN 'pull' THEN E'Start with the chest open and avoid shrugging the shoulders excessively.\nLead the motion with the elbows rather than yanking with the hands.\nPause briefly in the contracted position and return under control.'
      WHEN 'shoulder_accessory' THEN E'Set a stable torso and reduce unnecessary body swing before each rep.\nLift or separate the load under control while focusing on the target muscle.\nPause briefly near the top and lower slowly without dropping the tension.'
      WHEN 'curl' THEN E'Lock in the elbow position before you begin each repetition.\nCurl the weight without swinging the torso or changing wrist position excessively.\nSqueeze at the top and lower slowly through the full available range.'
      WHEN 'triceps_iso' THEN E'Set the elbow position first and keep the upper arm as still as possible.\nMove through the elbow joint with deliberate control rather than rushing the rep.\nFinish with a clear triceps squeeze, then return slowly without losing tension.'
      WHEN 'core' THEN E'Brace the midsection before the rep starts and keep the ribs and pelvis organized.\nMove slowly and avoid using momentum to create range of motion.\nFinish the rep without letting the lower back overextend or the neck take over.'
      WHEN 'olympic_lift' THEN E'Organize your stance and breathing first so the implement stays close to the body from the start.\nDrive through the floor explosively and time the pull, turnover, or catch without rushing the sequence.\nFinish each rep in balance and keep the bar path and rhythm as consistent as possible.'
      WHEN 'conditioning' THEN E'Start at a pace you can sustain while keeping the intended movement standard.\nAs fatigue rises, protect your breathing rhythm and avoid shortening the range just to move faster.\nUse recovery moments to reset posture and continue with controlled effort rather than sudden surges.'
      WHEN 'hinge' THEN E'Set the bar or implement close to the body and brace your core first.\nHinge from the hips instead of rounding or overextending the lower back.\nDrive the floor away and finish each rep with the hips and trunk arriving together.'
      WHEN 'lower_body' THEN E'Set your stance and brace your trunk before starting the descent.\nLower with control while keeping the knees tracking in a natural line with the feet.\nDrive through the full foot to stand up and finish without losing posture.'
      ELSE E'Set up in a stable position and organize your breathing before the rep begins.\nMove through the intended range without relying on momentum.\nFinish under control and repeat with the same technique on every rep.'
    END AS how_en
  FROM classified c
)
UPDATE exercises e
SET
  overview_ko = CASE WHEN e.overview_ko IS NULL OR e.overview_ko = '' THEN g.overview_ko ELSE e.overview_ko END,
  overview_en = CASE WHEN e.overview_en IS NULL OR e.overview_en = '' THEN g.overview_en ELSE e.overview_en END,
  why_ko = CASE WHEN e.why_ko IS NULL OR e.why_ko = '' THEN g.why_ko ELSE e.why_ko END,
  why_en = CASE WHEN e.why_en IS NULL OR e.why_en = '' THEN g.why_en ELSE e.why_en END,
  how_ko = CASE WHEN e.how_ko IS NULL OR e.how_ko = '' THEN g.how_ko ELSE e.how_ko END,
  how_en = CASE WHEN e.how_en IS NULL OR e.how_en = '' THEN g.how_en ELSE e.how_en END,
  description_ko = CASE
    WHEN e.description_ko IS NULL OR e.description_ko = '' THEN
      format(
        E'개요\n%s\n\n왜 하나요?\n%s\n\n수행 방법\n1. %s\n2. %s\n3. %s',
        g.overview_ko,
        g.why_ko,
        split_part(g.how_ko, E'\n', 1),
        split_part(g.how_ko, E'\n', 2),
        split_part(g.how_ko, E'\n', 3)
      )
    ELSE e.description_ko
  END,
  description_en = CASE
    WHEN e.description_en IS NULL OR e.description_en = '' THEN
      format(
        E'Overview\n%s\n\nWhy do this exercise?\n%s\n\nHow to do it\n1. %s\n2. %s\n3. %s',
        g.overview_en,
        g.why_en,
        split_part(g.how_en, E'\n', 1),
        split_part(g.how_en, E'\n', 2),
        split_part(g.how_en, E'\n', 3)
      )
    ELSE e.description_en
  END
FROM generated g
WHERE e.id = g.id
  AND (
    e.overview_ko IS NULL OR e.overview_ko = ''
    OR e.overview_en IS NULL OR e.overview_en = ''
    OR e.why_ko IS NULL OR e.why_ko = ''
    OR e.why_en IS NULL OR e.why_en = ''
    OR e.how_ko IS NULL OR e.how_ko = ''
    OR e.how_en IS NULL OR e.how_en = ''
    OR e.description_ko IS NULL OR e.description_ko = ''
    OR e.description_en IS NULL OR e.description_en = ''
  );

COMMIT;
